Repository figment-networks/figment-documentation, pull requests merged in 2022-11, with the labels that each got.

#203 DOCS-192 Add Cosmos Staking guide
  docs/guides/staking-api/Cosmos/staking/1_create-new-flow.mdx
  docs/guides/staking-api/Cosmos/staking/2_submit-delegation-data.mdx
  docs/guides/staking-api/Cosmos/staking/3_sign-delegate-transaction.mdx
  docs/guides/staking-api/Cosmos/staking/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Cosmos/staking/5_get-flow-status.mdx
  docs/guides/staking-api/Cosmos/staking/index.mdx
  docs/guides/staking-api/Cosmos/transfer/2_submit-transfer-data.mdx
Labels: documentation

#206 Add SOL Split Stake Flow Guide
  docs/guides/staking-api/Solana/split-stake/1_create-new-flow.mdx
  docs/guides/staking-api/Solana/split-stake/2_submit-split-stake-account-data.mdx
  docs/guides/staking-api/Solana/split-stake/3_sign-split-stake-account-transaction.mdx
  docs/guides/staking-api/Solana/split-stake/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Solana/split-stake/5_get-flow-status.mdx
  docs/guides/staking-api/Solana/split-stake/index.mdx
Labels: documentation

#208 DOCS-210 Add .env instructions to README
  .env-example
  README.md
Labels: documentation

#211 Rename prime-api.json to validator-api.json
  schemas/prime-api.json
  schemas/validator-api.json
Labels: enhancement

#212 update file name in generate.js
  generate.js
Labels: enhancement

#215 Update deployment Nov 8
  schemas/rewards-api.json
  schemas/validator-api.json
Labels: documentation

#217 Update deployment Nov 8
  schemas/rewards-rates-api.json
Labels: deployment

#218 Update deployment Nov 9
  schemas/staking-api.json
  schemas/staking-webhooks-api.json
Labels: deployment

#222 update deployment
  .gitignore
  generate.js
  package.json
  schemas/validator-api.json
  src/components/APIHomeRoute/index.jsx
  src/components/APIMethods/styles.module.css
  src/css/top-nav.css
Labels: deployment

#227 DOCS-220 Update Cosmos Transfer & Staking Flow
  docs/guides/staking-api/Cosmos/staking/1_create-new-flow.mdx
  docs/guides/staking-api/Cosmos/staking/2_submit-delegation-data.mdx
  docs/guides/staking-api/Cosmos/staking/3_sign-delegate-transaction.mdx
  docs/guides/staking-api/Cosmos/staking/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Cosmos/staking/5_get-flow-status.mdx
  docs/guides/staking-api/Cosmos/transfer/1_create-new-flow.mdx
  docs/guides/staking-api/Cosmos/transfer/2_submit-transfer-data.mdx
  docs/guides/staking-api/Cosmos/transfer/3_sign-transfer-transaction.mdx
  docs/guides/staking-api/Cosmos/transfer/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Cosmos/transfer/5_get-flow-status.mdx
Labels: documentation

#228 DOCS-226 Update `chain_code` for ETH Staking Flow
  docs/guides/staking-api/Ethereum/staking/1_create-new-flow.mdx
  docs/guides/staking-api/Ethereum/staking/2_submit-deposit-data.mdx
  docs/guides/staking-api/Ethereum/staking/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Ethereum/staking/5_get-flow-status.mdx
  docs/guides/staking-api/fireblocks-signing-transactions.mdx
  docs/guides/staking-api/staking-api-endpoints.mdx
  docs/guides/staking-api/working-with-staking-api-flows.mdx
Labels: documentation

#229 DOCS-202 DOCS-203 Add Polkadot Ledger and Nomination Proxy pages
  docs/guides/staking-api/Polkadot/ledger-accounts.mdx
  docs/guides/staking-api/Polkadot/nomination-proxy.mdx
  docs/guides/staking-api/validator-addresses.mdx
  static/img/guides/proxy/polkadot_apps.png
  static/img/guides/proxy/polkadot_apps_add_proxy.png
  static/img/guides/proxy/polkadot_apps_add_via_ledger.png
  static/img/guides/proxy/polkadot_apps_add_via_ledger_modal.png
  static/img/guides/proxy/polkadot_apps_connection.png
  static/img/guides/proxy/polkadot_apps_ledger_account_added.png
  static/img/guides/proxy/polkadot_apps_settings.png
  static/img/guides/proxy/polkadot_apps_staking_proxy.png
  static/img/guides/proxy/polkadot_ready.jpg
  static/img/guides/proxy/proxy_active.png
Labels: documentation

#231 DOCS-228 Update Staking API Overview Page
  docs/guides/staking-api/index.mdx
  docs/guides/staking-api/validator-addresses.mdx
  docs/quickstart/rewards-api.mdx
  docs/quickstart/staking-api.mdx
Labels: documentation

#232 DOCS-231 DOCS-230 DOCS-229 | Docs Update
  docs/guides/staking-api/figment-signing-transactions.mdx
  docs/quickstart/rewards-api.mdx
Labels: documentation
