Repository figment-networks/figment-documentation, pull requests merged in 2022-12, with the labels that each got.

#233 Update Support page
  docs/support.mdx
Labels: documentation

#235 DOCS-232 Add SOL Merge Stake Flow Guide
  docs/guides/staking-api/Solana/merge-stake/1_create-new-flow.mdx
  docs/guides/staking-api/Solana/merge-stake/2_submit-merge-stake-account-data.mdx
  docs/guides/staking-api/Solana/merge-stake/3_sign-merge-stake-account-transaction.mdx
  docs/guides/staking-api/Solana/merge-stake/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Solana/merge-stake/5_get-flow-status.mdx
  docs/guides/staking-api/Solana/merge-stake/index.mdx
Labels: documentation

#236 Update Deployment 12/06
  docs/guides/staking-api/Solana/merge-stake/1_create-new-flow.mdx
  docs/guides/staking-api/Solana/merge-stake/2_submit-merge-stake-account-data.mdx
  docs/guides/staking-api/Solana/merge-stake/3_sign-merge-stake-account-transaction.mdx
  docs/guides/staking-api/Solana/merge-stake/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Solana/merge-stake/5_get-flow-status.mdx
  docs/guides/staking-api/Solana/merge-stake/index.mdx
  schemas/rewards-api.json
  schemas/staking-api.json
Labels: deployment

#237 Update Deployment 12/06
  schemas/rewards-rates-api.json
Labels: deployment

#239 update deployement
  docusaurus.config.js
Labels: deployment

#241 paul/remove tx search
  README.md
  docs/quickstart/architecture.mdx
  docs/quickstart/transaction-search-api.mdx
  docusaurus.config.js
  src/pages/index.tsx
Labels: documentation

#192 DOCS-195 Add Staking API Webhooks Guide
  docs/guides/staking-api/staking-api-endpoints.mdx
  docs/guides/staking-api/staking-api-webhooks.mdx
Labels: documentation

#209 DOCS-195 Add API Proxy Guide
  docs/guides/proxy-requests.mdx
  docs/quickstart/api-authentication.mdx
  src/css/base-styles.css
  static/img/guides/proxy-requests/api_key_encrypt.png
  static/img/guides/proxy-requests/cf_200_response.png
  static/img/guides/proxy-requests/cf_add_code.png
  static/img/guides/proxy-requests/cf_add_vars.png
  static/img/guides/proxy-requests/cf_api_key.png
  static/img/guides/proxy-requests/cf_request.png
  static/img/guides/proxy-requests/cf_send_req.png
  static/img/guides/proxy-requests/cloudflare_dashboard.png
  static/img/guides/proxy-requests/cloudflare_request.png
  static/img/guides/proxy-requests/code_editor.png
  static/img/guides/proxy-requests/create_service.png
  static/img/guides/proxy-requests/env_vars.png
  static/img/guides/proxy-requests/environment_variables.png
  static/img/guides/proxy-requests/proxy_response_200.png
  static/img/guides/proxy-requests/proxy_send_post_request.png
  static/img/guides/proxy-requests/quick_edit.png
  static/img/guides/proxy-requests/save_and_deploy.png
  static/img/guides/webhooks/regex_explanation.png
Labels: documentation

#243 update deployment
  docs/guides/proxy-requests.mdx
  docs/guides/staking-api/staking-api-endpoints.mdx
  docs/guides/staking-api/staking-api-webhooks.mdx
  docs/quickstart/api-authentication.mdx
  src/css/base-styles.css
  static/img/guides/proxy-requests/api_key_encrypt.png
  static/img/guides/proxy-requests/cf_200_response.png
  static/img/guides/proxy-requests/cf_add_code.png
  static/img/guides/proxy-requests/cf_add_vars.png
  static/img/guides/proxy-requests/cf_api_key.png
  static/img/guides/proxy-requests/cf_request.png
  static/img/guides/proxy-requests/cf_send_req.png
  static/img/guides/proxy-requests/cloudflare_dashboard.png
  static/img/guides/proxy-requests/cloudflare_request.png
  static/img/guides/proxy-requests/code_editor.png
  static/img/guides/proxy-requests/create_service.png
  static/img/guides/proxy-requests/env_vars.png
  static/img/guides/proxy-requests/environment_variables.png
  static/img/guides/proxy-requests/proxy_response_200.png
  static/img/guides/proxy-requests/proxy_send_post_request.png
  static/img/guides/proxy-requests/quick_edit.png
  static/img/guides/proxy-requests/save_and_deploy.png
  static/img/guides/webhooks/regex_explanation.png
Labels: deployment

#246 Update Deployment 12/09
  .github/workflows/deploy.yml
  package.json
  schemas/rewards-api.json
  src/components/APIMethods/APIMethods.tsx
  src/utilities/reward-ranges.js
  yarn.lock
Labels: deployment

#247 Fix NEAR dynamic epoch range for Rewards API interactivity
  src/utilities/reward-ranges.js
Labels: documentation, enhancement

#248 Update Deployment 12/09
  src/utilities/reward-ranges.js
Labels: deployment

#249 DOCS-249 Fix line lighlighting
  docs/quickstart/staking-api.mdx
Labels: documentation

#251 DOCS-239 API Authentication details, collapsed by default
  partials/api-reference/making-calls.mdx
Labels: enhancement

#252 Update Deployment 12/15
  docs/quickstart/staking-api.mdx
  partials/api-reference/making-calls.mdx
  schemas/rewards-api.json
Labels: deployment

#261 Deployment Update
  docs/guides/staking-api/Cosmos/redelegate/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Cosmos/unstaking/1_create-new-flow.mdx
  docs/guides/staking-api/Cosmos/unstaking/4_submit-signed-transaction.mdx
  docs/guides/staking-api/Cosmos/unstaking/5_get-flow-status.mdx
  docs/guides/staking-api/figment-signing-transactions.mdx
  schemas/staking-api.json
  schemas/staking-webhooks-api.json
Labels: deployment
